branch-defaults:
  master:
    environment: Staging
environment-defaults:
  Staging:
    branch: null
    repository: null
global:
  application_name: Aggregate API
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Java 8 running on
    64bit Amazon Linux/2.5.2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
deploy:
  artifact: app/target/application.jar
